# Generated by Django 5.1.1 on 2025-11-09 15:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_id', models.CharField(db_index=True, max_length=100)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [
                    django.contrib.postgres.indexes.GinIndex(fields=['raw_data'], name='orders_raw_data_gin_idx'),
                    models.Index(fields=['date', 'status'], name='orders_date_status_idx'),
                    models.Index(fields=['customer_id', 'date'], name='orders_customer_date_idx')],
            },
        ),
    ]
